// <auto-generated />
namespace _3_Sahibinden.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class createSahibinden : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createSahibinden));
        
        string IMigrationMetadata.Id
        {
            get { return "202304060849046_createSahibinden"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
